name: Hello, World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello
        run: echo "Hello, World!"

      - name: Now it is
        run: date

      - name: Run ls -l
        run: ls -l
